spring:
  thymeleaf:
    cache: false
    check-template: true
    servlet:
      content-type: text/html
    check-template-location: true
server:
  port: 8080
chatroom-starter:
  websocketUrl: ws://localhost:8080/chat


